window.PAGES = [
  {
    "pdfPage": 1,
    "sourceText": "Internship Guide\nA learning handbook for your internship journey\nName:  \nAddress:  \nSchool:  \nStandard:\nTrade:\nEmployer Name:\nInternship Location: \nStart Date: \nEnd Date:",
    "type": "profile"
  },
  {
    "pdfPage": 2,
    "sourceText": "Child Protection & Safety\nYour safety is our priority. During your \ninternship, you have the right to feel safe, \nrespected, and protected.\nBe treated with respect and dignity.\nSay \"No\" to anything that makes you feel \nunsafe or uncomfortable.\nNever accept bullying, physical punishment, \nthreats, or unwanted touching. (Protected \nunder the POCSO Act, 2012 and the \nJuvenile Justice (Care and Protection of \nChildren) Act, 2015.)\nDo not share your personal information, \npasswords, or photos with anyone unless \nrequired by your school.\nIf you feel unsafe, inform your Vocational \nTeacher, School Teacher, Employer \nSupervisor, or Parent/Guardian \nimmediately.\nImportant Phone Numbers\nSave these numbers before you start your \ninternship. If you need help or feel unsafe, call \na trusted adult or one of these helplines.\n112 \u0013 Emergency\n100 \u0013 Police\n101 \u0013 Fire\n108 \u0013 Ambulance\n1098 \u0013\n Child Helpline\n\nWrite down these three numbers and keep \nthem handy:\nVocational Teacher: \nParent/Guardian:\nEmployer Supervisor:\nREMEMBER\nEvery child below 18 years is protected under Indian laws, including the \nPOCSO Act, 2012, the Juvenile Justice (Care and Protection of Children) \nAct, 2015, and the Child and Adolescent Labour (Prohibition and \nRegulation) Act, 1986 (amended in 2016).\nInternship Guide designed by fold:labs",
    "type": "safety"
  },
  {
    "pdfPage": 3,
    "sourceText": "Welcome to Your \nInternship Guide!\nThis guide will help you \nunderstand your \ninternship and build the \nskills you need to be \njob-ready!\nCongratulations on starting your internship journey!\nBut first; what is an internship?\nSay these words of affirmation to yourself \nevery morning for a fresh day:\nAn internship is a chance to work at a real \nworkplace for a short time. You try out a \njob, see how things work, and pick up skills \nyou will use for life. You are not expected \nto know everything \u0014 you are here to learn.\nI am ready for today.€\nI come on time, every day.€\nI watch, listen and ask questions.€\nI am here to learn.€\nI am kind to everyone around me.€\nI can do this!\nAn internship experience will help you gain:\nReal work experience\nUnderstanding of careers\nA chance to explore what you like doing\nHands-on learning\nImprove your employability skills\nWhenever you feel stuck, this guide will help \nyou figure it out.\n\nAll the best. \nLet's begin!\nRemember: this journey will be a learning \nexperience for you. There will be times when \nthings might get difficult. Do not give up! Try to \nenjoy every moment of it. When you look back \non your journey, you will see just how much you \nhave grown as a person!\nPicture from Electrical Internship\nPicture from Banking and Finance Internship\n01",
    "type": "welcome"
  },
  {
    "pdfPage": 4,
    "sourceText": "The Map to Your \nInternship Journey\nThis page is your map towards \nbecoming a more skilled and \nconfident version of yourself.\n\nEach step on the path shows \nwhere you are and what comes \nnext. As you move forward \neveryday, tick each checkpoint \nwhen you complete it. \nStart here!\nSTEP 1\nUnderstanding your \nInternship Journey\nThis section covers the basics on all that you \nwill need to know to have a great internship!\nPage 04\nRemember: Your employer is your \nworkplace mentor! Try to learn as \nmuch as you can from them!\nIntroduce yourself on the first day. \nTell them, \u001cI am looking forward to learning from you!\u001d\nMy Workplace Mentor\u0019s  Details\nMy mentor\u0019 s name is\nBusiness / Shop Name\n4 words you would use to describe them:\nIf you can, draw a \nquick sketch of your \nmentor! \n\nDon\u0019 t be nervous, this \nis just for fun.\nFill your mentor\u0019s details \nduring the first few \ndays of the internship!\nSTEP 2A\nInternship Journey Begins! \n- Initial Observations\nThis section guides careful observation of \nthe workplace before anything else begins.\nPage 10\n02",
    "type": "journey"
  },
  {
    "pdfPage": 5,
    "sourceText": "STEP 3\nThe Learn Better Method\nTowards the end of the internship, this \nsection reveals the learning method that \nwas quietly guiding you through your \ninternship learning journey.\nPage 34\nSTEP 4\nLook How Far You \nHave Come!\nA final section to look back, \nsee the growth that \nhappened and celebrate \nhow far the journey has \ncome.\nPage 36\nSTEP 2C\nInternship Journey Begins! \n- Your Daily Reflections\nThis is where the real learning \nhappens. Each day, progress towards \nthe goals is tracked, captured and \nbuilt upon.\nPage 14\nEnd here!\nWrite your name here\nSTEP 2B\nInternship Journey Begins! \n- Setting Your Internship Goals\nThis section helps turn \nobservations into clear and \nspecific goals for the internship.\nPage 12\nMy Achievement Board\nDaily Reflection Tracker\nThis Achievement Board is a space to \nrecord all your wins from your daily reflection \npages. Every time you reflect or collect a \nbadge, come here and colour it in!\nSummarising (\nBadge\nWord Map (\nBadge\n+\nAward Collection\nConsistency (\nBadge\n=\nLearn Better \nChampion Trophy\nDrawing (\nBadge\n03",
    "type": "map"
  },
  {
    "pdfPage": 6,
    "sourceText": "Step 1\nUnderstanding Your \nInternship Journey\nYou need to have the right tools with you \nbefore you start your journey. This section \nwill help you!\nKeep coming back to this \nsection whenever you need help! \nThis is your roadmap \u0014  before, during, and after your internship.\nBEFORE\nA. Before doing anything, complete these three important steps: \n1 Talk to parents about internship\n3 Ask parents to sign above documents\n2 Get your Consent Form, Child Protection \nPolicy & Safety Guidelines from your \ntrainer\n4 Get your Consent Form signed from \nparents & employers\nB. Where Can You Work?\nWrite your sector here:\nHere are sectors you can explore near you. Tick the boxes of the sectors you like:\nRetail\nBeauty & Wellness\nElectrical\nAutomotive\nFood Processing\nIT\nBanking & Finance\nApparel\nTourism & Hospitality\nHealthcare\nAgriculture & Gardening\nC. How to find an Internship?\n1.\n2.\nGet A Yes\nTell your trainer \nand parents first. \nIf they say no, try \nelsewhere.\n3.\nAsk Employers\nBe polite. Explain (\nthe internship \nprogramme. Can't \nfind one? Ask your \ntrainer.\nFind A Place\nLook for local \nsmall and medium \nemployers near you \ninstead of waiting for \nyour trainer.\n04\nQUICK TIP  \nDon't limit yourself to well-known brands. Local small and medium employers near home offer more \nhands-on learning. They may even offer you on after your internship.",
    "type": "before"
  },
  {
    "pdfPage": 7,
    "sourceText": "D. convincing your Parents\nTalking about the internship can feel new for them too \u0014  \nhere's how to make it easy.\nExplain It\nWhat an internship is\nHow it will benefit you\nTell them it is for 80 hours\nReassure Them \nShare your trainer's contact, \nemployer details and how you'll \ntravel\n1.\n2.\nBuild Trust \nObtain your parent's/guardian's \nconsent & ensure they sign the \nconsent form.\nAsk a past intern to share their \nstory\nStay Involved\nKeep sharing updates\nInvite them to visit your workplace \nand meet your employer\n3.\n4.\nRead about an intern\u0019s experience:\nI interned at a welding workshop \u0014  not a \ntrade many girls choose, but I loved it. \nConvincing my parents took time, but the \nabove 4 tips helped me. Don't give up! \nWe never thought she could intern in a \nwelding workshop. She made us realise girls \ncan do anything!\nAlumni\nD\nURING \nE. For a Successful Internship\nDO\nDON\u0019 T\nBe late, absent or use your phone \nat work\nIntroduce yourself to your employer (\non the first day\nDress inappropriately - wear your \nschool uniform\nUnderstand your role and \nresponsibilities from your employer\nBe polite, respect everyone \nask questions and add value\nFight over small issues \nSkip informing your employer in an \nemergency\nUse the Daily Reflection Pages\nExpect payment - focus on the \nlearning\nComplete a minimum of 80 hours (\n(3 hours per day)\n05\nOjaswi\u0019s Parents",
    "type": "during"
  },
  {
    "pdfPage": 8,
    "sourceText": "F. Internship Consent & Confirmation Form\nInternship Details\nSchool Name: \nTrade/Job Role:\nStudent Name:\nInternship Organisation:\nClass (circle your class): XI / XII \nEmployer Confirmation\nWe agree to provide internship opportunities to the above student and will:\nProvide a safe and supportive learning environment.\nGuide the student in trade-related work.\nMonitor attendance and learning during the internship.\nInform the school before extending internship hours.\nFollow all applicable child protection and workplace safety laws, including \nthe POCSO Act, 2012 and the Prevention of Sexual Harassment (POSH) \nAct, 2013.\nStudent & Parent Consent\nI understand that this internship is part of the vocational education programme and agree to \nfollow all workplace rules, safety guidelines, and instructions provided by the employer and \nschool.(\nI also understand that travel to and from the internship workplace is my/my ward's \nresponsibility. In case of any emergency or safety concern, I will immediately inform the \nschool, Vocational Trainer, employer, or parent/guardian.\nSignatures\na. Student\nd. Headmaster/Principal\nName: \nName: \nSignature:\nSignature:\nb. Parent/Guardian\nSeal:\nName: \nSignature:\nb. Vocational Trainer\ne. Employer\nName: \nName: \nSignature:\nSignature:\nSeal:\nRemember: You cannot start \nyour internship without a \nsigned copy of the  Consent \nForm, Child Protection Policy & \nSafety Guidelines \nDuration:  From \nTo\n06",
    "type": "consent"
  },
  {
    "pdfPage": 9,
    "sourceText": "G. How to Stay safe at your internship\nRead this comic to understand good safety practises:\nSafety guide before you start your internship\nWoohoo! Got my \nInternship! Can\u0019 t \nwait to learn more.\nShared my \ninternship \ndetails with my \nparents\u0014where, who, when, and how I\u0019\nll get \nthere.\nBasics \nchecked! My \nemployer\u0019s \nname, the shop address, phone number, (\noperating \nhours\nJust in \ncase! \nImportant \nnumber \nsaved.\nSafety first! (I\u0019\nve read the \nsafety rules. \nUnderstanding \nthe rules keeps \nme safe.\nMy privacy \nmatters! I won't \nshare personal \ninfo with \nstrangers.\nStaying alert!!!\nI will report anything unsafe \nto my supervisor or teacher.\nKindness online is key.\nI won\u0019 t post anything on \nsocial media that could \nupset or hurt others.\nI\u0019 ll always wear \nthe right safety \nequipment to \nstay protected.\n07",
    "type": "safety_comic"
  },
  {
    "pdfPage": 10,
    "sourceText": "H. Employability Skills You WiIl Build\n1.\nCommunication: Speak clearly. \nRe-read before you send.\n2.\nProblem Solving: Try a few \nsolutions. Ask for help.\n3.\nActive Listening: See, hear and \nrepeat to confirm.\n4.\nTime Management: Complete all \nyour tasks on time.\n5.\nTeamwork: Offer to help. Hear (\nothers out.\n6.\nTaking Initiative: See something (\nto do? Do it and add value.\nAFTER\nOnce you have successfully completed your internship, remember to do the following:\n1 Submit your Internship Report\n2 Collect your Certificate\n3 Share honest feedback on the QR code below\nTo access the feedback form, \nscan this with your phone camera!\n08",
    "type": "skills_after"
  },
  {
    "pdfPage": 11,
    "sourceText": "Step 2\nInternship Journey Begins!\nThis section has three parts:\nField Observations: Your first few \ndays at your internship are for \nobserving. Just look around and \nwrite down what you see.(\nIf your internship is 15 days long, \nuse Days 1 and 2 for observation. \nIf it is 30 days long, then use the \nfirst 4 days.\nSetting Your Internship Goals: Once \nyou have observed, you will use \nwhat you noticed to set your main \ninternship goals. \n\nDaily Reflection Pages: Your daily \nreflections will then help you track \nyour progress towards each goal, \none step at a time.\nPicture from Apparel and Fashion Internship\n05\n09",
    "type": "step2"
  },
  {
    "pdfPage": 12,
    "sourceText": "Step 2A\nInitial Observations\nFill in all the sections here over the \ncourse of your observation days. Be as \nspecific as you can.\nI will take my time to \nobserve and learn \nmore about my \ninternship. \nWhat Skills Did You Notice on the field?\nTick the skills you noticed from the list below:\nOther skills I noticed, but were not in the list:\nManaging time properly\nWorking well with others in a team\nProblem solving\nKeeping the space neat and tidy\nHandling customer complaints\nSpeaking confidently and clearly\nBeing open to feedback\nKnowing proper tools/programs to use\nTaking initiative\nListening with attention\nBehaving politely with everyone\nBeing attentive and alert\nCircle 2-4 skills you want to learn during your internship from the above lists. \nInternship Safety Checklist\nTrade specific Skills\nAs you observe, tick the ones you find \nanswers for: \nScan the QR code below to know more!\nI know where the first aid kit is\nI know the safety rules at my workplace\nI know which tools or equipment need to \nbe handled carefully\nI know where the fire exit is\n I know who to go to if something feels \nunsafe\nKeep these in mind for the rest of your \ninternship as well.\n10",
    "type": "observations"
  },
  {
    "pdfPage": 13,
    "sourceText": "What Tools or Machines are being used?\nUse this space to write or draw what you see\nWhat are some things you found interesting?\nDid you observe anything new and cool?\n1.\n2.\nDid anything surprise you? \n1.\n2.\nAnything you found useful you would like to learn? \n1.\n2.\nWhat you write here will help you set your \ninternship goals in the next section!\n11",
    "type": "observations2"
  },
  {
    "pdfPage": 14,
    "sourceText": "Step 2B\nSetting Your \nInternship Goals\nFill these pages carefully! Try to have 4 \ngoals for your internship. \nA good goal tells you\nwhat you want to learn\nwhy it matters to you \nIt also tells you how you can \ntrack your progress!\nEvery great internship journey starts with setting clear learning goals. \nWithout them, it is easy to lose track of what you are trying to learn. \n\nLook at your observations. Think about what you want be able to learn by the end of \nthe internship. \n\nThen set 3 to 4 goals for yourself. These goals will help you achieve what you want \nin a clear step by step manner.  \n\nDiscuss your internship trade specific goals with your Vocational Trainer and \nEmployer.\nGOAL #1\nA. What specific skill do you want to learn: \nB. Why this is important to you:\nExample: I want to learn how to talk to customers \nconfidently (communication skills)\nExample: Every time a customer walked in this week, I \ngot nervous and could not talk. Could not even say hello.\nNow lets break your goal into 4 sub-goals\nExample: Watch how my employer greets and talks to \ncustomers, greet and talk to at least one customer with \nemployer nearby for support, greet and talk to \ncustomers on my own without needing help\nHow will you know you\u0019re making progress (\nExample: I will be able to describe the exact steps \nemployer follows when a customer walks in and be able to \nfollow them exactly on my own\n12",
    "type": "goal"
  },
  {
    "pdfPage": 15,
    "sourceText": "GOAL #2\nA. What specific skill do you want to learn: \nB. Why this is important to you:\nNow lets break your goal into 4 sub-goals\nHow will you know you\u0019re making progress\n \nGOAL #3\nA. What specific skill do you want to learn: \nB. Why this is important to you:\nNow lets break your goal into 4 sub-goals\nHow will you know you\u0019re making progress\n \nGOAL #4\nA. What specific skill do you want to learn: \nB. Why this is important to you:\nNow lets break your goal into 4 sub-goals\nHow will you know you\u0019re making progress\n \n13",
    "type": "goal"
  },
  {
    "pdfPage": 16,
    "sourceText": "Step 2C\nYour Daily \nReflections\nReflection means \nwriting about what \nhappened, what you \nlearned and why it is \nimportant.\nUse the goals and sub-goals you have written \npreviously to guide your reflections.  \nReflect every day. Be honest and specific.\nReflections are an important part of your internship. (\nThey will help you see the progress you make with all that you learn. (\nHere are two things to keep in mind with the daily reflections:(\nQUICK TIP\nIf you need more space (\nto write, then use your own \nsheets! Remember to stick \nthem in this guide on the \ncorrect pages! \nYou will meet many new people at your internship. (\nWrite down who you met and what you learned from them. Try to write about at least 4 people.\nNew People I Met During My Internship\n1. Name: \nWhat they do:\nWhat I learned from them:\n2. Name: \nWhat they do:\nWhat I learned from them:\n3. Name: \nWhat they do:\nWhat I learned from them:\n4. Name: \nWhat they do:\nWhat I learned from them:\nThere is an example of how you can fill in your daily reflection pages on the next page. \nTurn to have a look!\n14",
    "type": "reflection_intro"
  },
  {
    "pdfPage": 17,
    "sourceText": "record Your New knowledge\nNote down all the important things you \nare learning today\nExample Daily Reflection Page\nI want to talk to customers confidently\nGoal : \nWatch how to greet and talk to customers, like Rita didi, my mentor at work\nSub-goal : \nQUICK TIP #2\nUse short points to \nmake fast notes.\nQUICK TIP #1\nWrite down the important \nthings you are learning today. \nTry to connect them to your \nsub-goal. \n-\n-\n-\n-\ncustomer could not find blue t-shirt in his size, was upset. Rita didi \n(RD) listened to him, then checked stocks and found his size. Customer \nwas happy, he bought t-shirt.\nRita didi looks at customer, smiles, says \"hello, how can I help you \ntoday?\"\nRD speaks slowly + clearly with every customer, listens carefully. \nIf she does not know answer for something, she stays calm and asks \ncustomer to give her a minute as she needs to ask Anuja Ma\u0019am (boss)\nWas taught how to stock products, check for faulty pieces + \nhow bills are made when customer buys something\n-\n-\n-\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nQUICK TIP #3\nSummarising is one great (\nway to revise important tasks \nyou learned. A good summary \nis short and in your own words. \nQUICK TIP #4\nThink of something you already (\nknow that works in a similar way. \nWrite down what makes them similar.\nStaying calm+ listening is something I know. I do the same when my younger \ncousin is upset just like RD did \nI know how to speak slowly + clearly because I do the same when I explain \nsomething to my grandmother. RD does this with customers for the same reason \nI know how to greet people, I greet my neighbours and friends, I just need to \npractise greeting people I do not know\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3\nC\nonnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nINCORRECT SUMMARISING\nI observed how Rita didi greets customers at the store.\nCORRECT SUMMARISING\nRD is patient + calm. Smiles and looks at customer, says \nhello how can i help you. Listens to customers carefully. \nDoes not stress when she does not know answer, checks with \nboss before answering. Always polite. \n05\n15",
    "type": "reflection_example"
  },
  {
    "pdfPage": 18,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK  TIP #5\nFeedback can improve your \nlearning by up to 30%! Make sure \nyou ask your mentor to check \nyour notes to see if you have \nincluded everything. \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\n04\n04\n16\nRemember: Talk to your \nemployer/ workplace mentor \nabout your daily tasks.\nDid you finish your assigned \ntask for today?\nYes\nNo\nCongratulations on completing your first reflection! (\nGo to page 03 and colour in a star on your \nAchievement Board. Do this after every reflection. \nThis reflection journey has some special badges for \nyou to unlock. Try to collect them all!\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection"
  },
  {
    "pdfPage": 19,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nDid you learn something \nnew that surprised you? \nColour your answer!   \nYes\nNo\nWrite in 1 sentence what \nyou learned or want to \nlearn: \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nQUICK  TIP #6\nTeaching others what you learned \nhelps you remember it better by 16%! \nTry teaching one thing you learned to \nyour parents.\n01 sub-goal 1\nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3\n17\nsub-goal 2 05",
    "type": "reflection_quiz"
  },
  {
    "pdfPage": 20,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK  TIP #7\nWrite in the language (\nyou are comfortable with. \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nChallenge Time! You\u0019ve been practising summarising. Complete this quiz to collect a special badge!  (\nTick the correct answer.\nQ1. A good summary is:\nQ2. After summarising, you should:\na) Long & detailed\na) Get feedback from your mentor\nAnswer\nQ1. b   Q2: a\nb) Short & in your own words\nb) Forget about it and move on\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n18\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_quiz"
  },
  {
    "pdfPage": 21,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nQUICK  TIP #8\nTry teaching what you have learned \nto your friends. Ask them to say \u001cwhat if\u001d\n after everything you say. \nThis will help you connect your old & \nnew knowledge.\nCongratulations! (\nYou are a Summarising Champion. (\nTick to collect your badge.\nRemember to record this win on your \nAchievement Board (page 03).\nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n19\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_badge"
  },
  {
    "pdfPage": 22,
    "sourceText": "Example Daily Reflection Page\nI want to talk to customers confidently\nGoal : \nWatch how to greet and talk to customers, like Rita didi, my mentor at work\nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK  TIP #9\nWord maps, like this, are another \ngreat way to organise information. \nIt can be used to organise new \nprocesses you learn during your \ninternship. \ncustomer walks in\neye contact + smile at customer\nsay hello and ask how you can help them\nhappy or unhappy customer - listen \ncarefully, stay calm and be patient\nif don\u0019t know answer \nto customer\u0019s question \nfind the product or answer\ndo they want to buy?\nstay calm\nyes\nno\n politely ask them to \nwait a minute \nthank them and \nlet them go\nthank them and \nprocess the \npayment\nask Anuja ma\u0019am \nQUICK TIP #10\nYou can use \nsummarising or mapping \nto organise new \nknowledge. \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nRemember to share your photo or \nvideo of the week with your VT, \nparents and peers!\nGoal Check-In Time! (\nYou\u0019ve been doing a great job so far! Now is a good time to check your progress. (\nShare this with your VT, employer, parents and peers!\nQ1. Are you on track with your goal? \nYes!\nA little\nNot yet\nQ2. What were 3 highlights of the week?\nQ3. What improvements did I makke to reach my goal?\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n20\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced",
    "type": "reflection_example2"
  },
  {
    "pdfPage": 23,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nQUICK  TIP #11\nUse arrows and \nconnectors to show the \nsequence of information \nin your word maps. \nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nCongratulations on coming this far in your \nreflection journey! (\nRemember to colour in a star on your Achievement \nBoard on page 03. Do this after every reflection. \nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n21\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection"
  },
  {
    "pdfPage": 24,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nDid you learn something \nnew that surprised you? \nColour your answer!   \nYes\nNo\nWrite in 1 sentence what \nyou learned or want to \nlearn: \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nQUICK  TIP #12\nPretend you are teacher and your \nsiblings/friends are your students. \nTeach them something new you have \nlearnt. This will show you if you have \nany gaps in your understanding. \nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n22\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection"
  },
  {
    "pdfPage": 25,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK  TIP #13\nIf you need more space \nto write, use your own \nsheets and stick it here!\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nChallenge Time! You\u0019 ve been practising how to use word maps. Complete this quiz to collect a \nspecial badge! Fill in the correct answer.\nQ1. Word maps help organise  \nQ2. Word maps show how things are \n.\n.\na) processes\na) different\nAnswer\nQ1: a   Q2:b \nb) stories\nb) connected\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n23\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_quiz"
  },
  {
    "pdfPage": 26,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK  TIP #14\nDo not feel shy to ask (\nyour mentor if you are \nconfused or did not \nunderstand what you \nlearned. This will help you \nlearn better.\nOrganise New Knowledge\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nCongratulations! (\nYou are a Word Map Champion. (\nTick to collect your badge.\nRemember to record this win on your \nAchievement Board (page 03).\nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n24\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_badge"
  },
  {
    "pdfPage": 27,
    "sourceText": "Example Daily Reflection Page\nI want to get better at being organised\nGoal : \nLearn how to package and store inventory\nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nHeating plate\nmelts the plastic \nto seal the bag\nPressing Arm(\npush down to close \nseal evenly\nQUICK TIP #15\nYou can also organise information \nthrough drawings, like shown here. It \nis best used to document new tools \nand machines you learn about.\nif the bag is not flat \nhere, the seal comes \nout uneven\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nPower button\nmust be off before \nchanging the bag \nposition\nTimer\ncontrols the heat, too \nlong can burn the bag\nfresh snacks\nQUICK TIP #16\nYou can use summarising, mapping or \ndrawing to organise new knowledge. \nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nRemember to share your photo or \nvideo of the week with your VT, \nparents and peers!\nGoal Check-In Time! (\nYou\u0019ve been doing a great job so far! Now is a good time to check your progress. (\nShare this with your VT, employer, parents and peers!\nQ1. Are you on track with your goal? \nYes!\nA little\nNot yet\nQ2. What were 3 highlights of the week?\nQ3. What improvements did I makke to reach my goal?\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n25\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_example3"
  },
  {
    "pdfPage": 28,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nDid you learn something \nnew that surprised you? \nColour your answer!   \nYes\nNo\nWrite in 1 sentence what \nyou learned or want to \nlearn: \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nQUICK TIP #17\nRough sketches as drawings \nare enough. Label everything. \nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nCongratulations for coming this far! (Here is your Consistency Badge.  (\nTick to collect it.\nRemember to record this win on your \nAchievement Board (page 03).\nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n26\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_badge"
  },
  {
    "pdfPage": 29,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nQUICK TIP #18\nDrawing what you learn helps you \nunderstand it better 93% more than \njust writing. Practise drawing when you \nlearn about a new machine or tool.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3\n27",
    "type": "reflection"
  },
  {
    "pdfPage": 30,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK TIP #19\nEven if you learn something new and \ninteresting not related to your goal, \nwrite it down! You are here to learn, \nmake the most of it.\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nChallenge Time! You\u0019 ve been practising how to use drawings. Complete this quiz to collect a \nspecial badge! Tick true or false.\nQ1. A drawing needs to look perfect to be useful.\nTrue\nFalse\nQ2. You should label each part of the drawing.\nTrue\nFalse\nAnswer\nQ1: False   Q2:True   Q3: True \nQ3. Drawings can help understand new tools.\nTrue\nFalse\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n28\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_quiz"
  },
  {
    "pdfPage": 31,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nDid you learn something \nnew that surprised you? \nColour your answer!   \nYes\nNo\nWrite in 1 sentence what \nyou learned or want to \nlearn: \nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nQUICK TIP #20\nYou can use summarising, mapping or \ndrawing to organise new knowledge. \nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nCongratulations! (\nYou are a Drawing Champion. (\nTick to collect your badge.\nRemember to record this win on your \nAchievement Board (page 03).\nDid you finish your assigned \ntask for today?\nYes\nNo\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3\n29",
    "type": "reflection_badge"
  },
  {
    "pdfPage": 32,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nQUICK TIP #21\nPractise all three techniques - \nsummarising, word mapping & drawing \nwherever you think it is needed. \nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nRemember to share your photo or \nvideo of the week with your VT, \nparents and peers!\nYes\nNo\nGoal Check-In Time! (\nYou\u0019ve been doing a great job so far! Now is a good time to check your progress. (\nShare this with your VT, employer, parents and peers!\nQ1. Are you on track with your goal? \nYes!\nA little\nNot yet\nQ2. What were 3 highlights of the week?\nQ3. What improvements did I makke to reach my goal?\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n30\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_checkin"
  },
  {
    "pdfPage": 33,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nQUICK  TIP #22\nNow you know all about (\ntaking good notes, organising \nthem & learning from them. \nYou can continue this in any \nother notebook! Don\u0019t let \nthese pages limit you.\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nChallenge Time! You\u0019 ve been learning and reflecting about new things. This is a big accomplishment, \ngreat job! Complete this last quiz to earn your final badge! Tick the correct answer.\nQ1. You cannot teach what you learned to your \nfriend. What does this mean?\nQ2. How should you start your daily reflections?\na) Write whatever catches your attention \na) You need to ask your mentor for help\nb) Focus on important & new knowledge\nAnswer\nQ1: a   Q2: b \nb) It was not important\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n31\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "reflection_quiz"
  },
  {
    "pdfPage": 34,
    "sourceText": "Goal : \nSub-goal : \nrecord Your New knowledge\nNote down all the important things you \nare learning today\nCollecting all 4 badges = Champion Trophy\nYou are a Learn Better Champion! (\nThis is a big deal! Be proud.\nTick to collect your trophy.\nRemember to record this win on your \nAchievement Board (page 03).\nOrganise New Knowledge\nNow organise the information into \nshort summary paragraphs, \ndrawings or word maps.\nConnect Old & New knowledge\nNote down how this connects to things \nyou already know or have experienced\nDid you finish your assigned \ntask for today?\nYes\nNo\nCONGRATULATIONS! You have successfully reached the end of your internship reflections! \nBe very proud of what you have achieved. \nWhat you don\u0019t know is that you have used \na special learning method during your \ninternship! (\nCurious? Read page 34.\nWere you able to complete your goals? \nYes!\nAlmost..\nLooking back, how do you think you did? \n(Write one line here:\nThis is your Goal Tracker. Every time you achieve your sub-goal, colour it in here!\nGOAL 1\nGOAL 2\nGOAL 3\nGOAL 4\n32\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 1\nsub-goal 2\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 4\nsub-goal 3\nsub-goal 3\nsub-goal 3\nsub-goal 3",
    "type": "trophy"
  },
  {
    "pdfPage": 35,
    "sourceText": "Step 3\nDid you know you were using a \nsecret way of learning all along?\nI feel I have learnt a lot during my internship! \nThere were clear learning steps for me to \nfollow. That was helpful.\nYes! I also liked the tips that were \ngiven on how to observe, make my \nnotes and think about what I was \nlearning. (\nI wonder if this method has a name.....\n05\n05\n33",
    "type": "method_intro"
  },
  {
    "pdfPage": 36,
    "sourceText": "Step 3\nLearn Better \nMethod\nYou have have been using the Learn Better Method throughout your internship. (\nYou just didn\u0019t know it! Let\u0019s see how:\n2\n1\nSetting goals\nMaking a plan\nYou started your learning journey \nby setting goals for the skills you \nwanted to learn. \nYou then broke your goals into \nsmaller steps as sub-goals. This \nhelped you make a plan for your \nlearning. \n3\n4\nDaily meaningful reflection\nChecking Your Progress\nYour daily reflections not only \nhelped you reflect, but it also  \nhelped you understand how you \nlearned during your internship.\n\nThis improved your learning \npractise meaningfully and helped \nyou check your progress.  \nYou used 3 deep reflection tools: \nsummarising, word maps and \ndrawings.\n (\nOn every reflection page, you also: (\na. Recorded important information(b. Organised using deep reflection tools(\nc. Connected it to what you already \nknew\nThis internship has \ntaught me that I can \nlearn anything I want to! \nWe call this process the Learn Better Method, \nand this workbook helped you practise it! \nNow you can use this same method for anything \u0014 a \nnew job, a new skill or anything else you want to learn. \nYou have done it once. You can do it again!\n34",
    "type": "learn_better"
  },
  {
    "pdfPage": 37,
    "sourceText": "Step 4\nWhat have you learnt so far?\nCongratulations! You have successfully \ncompleted your internship! Pat yourself \non the back and be proud of the \njourney you have finished. \nYou should now take a moment to \nstop and reflect on all the skills you \nhave gained from them this internship. \nPicture from Retail Internship\nPicture from Electrical and Electronics Internship\n05\n35",
    "type": "completion"
  },
  {
    "pdfPage": 38,
    "sourceText": "Step 4\nLook How Far \nYou\u0019 ve Come!\nYou have learnt through this internship \nthe importance of reflecting. We learn \nbetter when we reflect. \nThink about all the skills you have learnt during \nyour internship. \nYou will now rate yourself on the skill levels for \nthem, before and after the internship. This will \nhelp you see your progress!\nREMEMBER!\nBe honest. This is not a test, but a (\nproud moment for you to see your \nprogress.\nUse this guide to rate:\n: Did not know this\nIt is natural to have not learnt all the skills \nyou wanted to during your internship. \n: Know this a little\n: Know this well\nEmployability Skills\nSkill level before \nInternship\nSkill level after \nInternship\nCommunication Skills (\nSharing your thoughts clearly \u0014  whether you are \nspeaking or writing.\nProblem Solving(\nFinding a way forward when something goes \nwrong or doesn't go as planned.\nActive Listening(\nGiving full attention when someone speaks to \nreally understand what they mean.\nTaking Initiative(\nDoing something useful without being asked to.\nTeamwork(\nWorking with others towards a shared goal, even \nwhen people think differently.\nTime Management (\nPlanning your tasks so that the right things get \ndone at the right time.\nIf there are more skills you have learnt and \nthey are not listed above, write them below:\nNo. of hours completed: \n1.\nDid you feel safe during the internship?\nYes\nNo\n2.\n3.\n36\nStart here!\nEnd here!\nYou have come a long way! Let\u0019 s \nlook at your progress.",
    "type": "self_assessment"
  },
  {
    "pdfPage": 39,
    "sourceText": "You might be wondering what\u0019 s next after completing your internship. Here is what you can do:\nFinding your path after the internship\nHigher Education \nSkilling and Jobs\nAfter Class 10: ITI, Diploma, junior \ncollege (11th & 12th)(\nAfter Class 12: BCom, BCA, Engineering \nand more\nTata Strive, PMKVY: free job-ready \ntraining across trades\nNot sure which path is right? Talk to your \ntrainer, your family, or do your own \nresearch. (There's no single right path \u0014\n choose what's \nright for you!\nPaid Apprenticeship\napprenticeshipindia.gov.in: earn while \nyou train, Class 8+\nFind words to help your next journey! \nFind these words:\n\u0010€ APPRENTICE\n\u0010€ FUTURE\n\u0010€ PATHWAY\n\u0010€ CAREER\n\u0010€ GOALS\n\u0010€ SKILL\n\u0010€ CERTIFICATE\n\u0010€ INTERNSHIP\n\u0010€ TEAMWORK\n\u0010€ DIPLOMA\n\u0010€ JOB\n\u0010€ TRADE\n\u0010€ EMPLOYER\n\u0010€ LEARNING\n\u0010€ TRAINING\nt\nl\nx\nq\nf\nl\ne\na\nr\nn\ni\nn\ng\ne\nr\nl\nj\nf\nq\nf\nc\nd\nm\np\nj\no\nb\ne\ny\ne\nz\nz\nz\ng\nj\ne\nf\nu\nt\nu\nr\ne\nt\nb\ny\np\nk\nt\nr\na\ni\nn\ni\nn\ng\nb\nt\na\nu\no\nm\na\nm\no\nl\np\ni\nd\nc\ni\nw t\nc\nw l\nl\nl\ni\nk\ns\nf\nu\nz\nn\nh\nt\ne\ni\ny\np\nt\nr\na\nd\ne\nm\ns\nt\nt\ng\nc\np\nf\na\nm\nf\ns\ng\nb\nm\nl\ne\nq\nf\ni\nm\nl\ni\nw e\nd\ne\nh\nx\na\nr\ng\nb\nt\nr\ny\nv\nt\nh\nb\nv\nk\nd\no\nn\nm\nt\nn\no\nr\nr\nu\nr\nt\ny\nj\nu\ng\ns\nn\nj\ne\ns\nh\ne\nn\nm\ne\na\nv\nl\no\nh\nq\no\nr\nf\na\na\ne\nt\np\nc\np\no\nh\ni\no\ny\np\nt\ny\no\nf\nr\nz\np\nm\nd\nc\np\ne\nl\np\nn\nl\nc\nt\ne\na\nm\nw o\nr\nk\nz\no\na\nq\nq\nv\nb\nb\nu\nc\ne\nc\nx\nk\ny\nGreat job finding all the words!\n\nNow, take a moment to think about your future and answer these questions:\n\nQ1. After completing Class 10/12, would you like to continue studying or working in the same trade?\n\u0010 Yes\u0003 \u0003 \u0010 No\n\nQ2. If your answer is \"No\", which trade or career would you like to explore?\n37",
    "type": "future"
  },
  {
    "pdfPage": 40,
    "sourceText": "Employer Feedback\nStudent Name: \nRate the student\u0019 s workplace skills.\nSkill\nAttendance & Punctuality\nProfessional Behaviour\nLearning Ability\nCommunication\nTechnical Skills\nProblem Solving\nOne strength of the student:\nOne area for improvement:\nEmployer Name & Signature:\n38",
    "type": "employer"
  }
];
